language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer update

script:
  - mkdir -p build/logs
<<<<<<< HEAD
  - vendor/bin/phpunit tests/
=======
  - vendor/bin/phpunit -c phpunit.xml.dist --verbose
>>>>>>> e9319514d133835695af5709af11c221116efb1c
